import type { Metadata } from "next"
import localFont from "next/font/local"
import { Toaster } from "sonner"

import TanstackProvider from "@/providers/TanstackProvider"
import Layout from "@/web/components/customs/Layout/Layout"
import "../globals.css"

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
})
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex items-center justify-center`}
      >
        <TanstackProvider>
          <Layout>
            {children}
            <Toaster position="bottom-right" richColors />
          </Layout>
        </TanstackProvider>
      </body>
    </html>
  )
}
