import type { Metadata } from "next"
import localFont from "next/font/local"
import React from "react"
import { Toaster } from "sonner"

import { auth } from "@/auth"
import TanstackProvider from "@/providers/TanstackProvider"
import Layout from "@/web/components/customs/Layout/Layout"
import { ThemeProvider } from "@/web/components/theme-provider"
import { AppContextProvider } from "@/web/hooks/useAppContext"
import "../globals.css"

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
})
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full flex items-center justify-center`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppContextProvider session={session}>
            <TanstackProvider>
              <Layout>
                {children}
                <Toaster position="bottom-right" richColors />
              </Layout>
            </TanstackProvider>
          </AppContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
